spring:
  application:
    name: customer
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: customerdb

server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

customer:
  ms-account-api: http://ACCOUNT/api/v1/account
  ms-credit-api: http://CREDIT/api/v1/credit/customer