spring:
  data:
    mongodb:
      uri: mongodb+srv://irazabarob44:XrRPi6r4tNfxyEhN@cluster0.g32atsl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: creditdb

server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://ms-eureka:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

credit:
  ms-transaction-api: http://TRANSACTION/api/v1/transaction
  ms-customer-api: http://CUSTOMER/api/v1/customer/customers