spring:
  application:
    name: ms-eureka

server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://ms-eureka:8761/eureka/
