spring:
  application:
    name: ms-eureka
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: yankiddb

server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
