server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://ms-eureka:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-customer
          uri: lb://MS-CUSTOMER
          predicates:
            - Path=/api/v1/customer/**

        - id: ms-account
          uri: lb://MS-ACCOUNT
          predicates:
            - Path=/api/v1/account/**

        - id: ms-credit
          uri: lb://MS-CREDIT
          predicates:
            - Path=/api/v1/credit/**

        - id: ms-transaction
          uri: lb://MS-TRANSACTION
          predicates:
            - Path=/api/v1/transaction/**

        - id: ms-debitcard
          uri: lb://MS-DEBITCARD
          predicates:
            - Path=/api/v1/debitcard/**

        - id: ms-yanki
          uri: lb://MS-YANKI
          predicates:
            - Path=/api/v1/yanki/**
  config:
    label: develop