server:
  port: 8083

spring:
  application:
    name: ms-report
  data:
    mongodb:
      uri: mongodb://localhost:27017/reportdb

  cloud:
    config:
      uri: http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
