spring:
  application:
    name: ms-yanki
  data:
    mongodb:
      uri: mongodb://localhost:27017/yankidb

  cloud:
    config:
      uri: http://localhost:8888

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: my-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


yanki:
  ms-debitcard-path: http://MS-DEBITCARD/api/v1/account
